import { useState, type ChangeEvent } from "react";

import type { TaskTemplateRunNowInput, UploadTaskContextAttachmentInput } from "@cc/shared/schemas";

import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { buttonVariants } from "@/components/ui/button-variants";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

type Props = {
  taskTitle: string;
  busy?: boolean;
  onCancel: () => void;
  onRun: (input?: TaskTemplateRunNowInput) => void;
};

export function RunTaskContextDialog(props: Props) {
  const [contextText, setContextText] = useState("");
  const [attachments, setAttachments] = useState<UploadTaskContextAttachmentInput[]>([]);

  function handleRun() {
    const text = contextText.trim();
    props.onRun(
      text || attachments.length > 0
        ? {
            context: text ? { text, attachments: [] } : undefined,
            contextAttachmentUploads: attachments,
          }
        : undefined,
    );
  }

  async function handleUpload(event: ChangeEvent<HTMLInputElement>) {
    const files = Array.from(event.target.files ?? []);
    event.target.value = "";

    const uploads = await Promise.all(
      files.map(async (file) => ({
        filename: file.name,
        mimeType: file.type,
        sizeBytes: file.size,
        dataUrl: await readFileAsDataUrl(file),
      })),
    );
    setAttachments((current) => [...current, ...uploads]);
  }

  return (
    <Dialog onOpenChange={(open) => !open && props.onCancel()} open>
      <DialogContent
        className="max-w-xl p-5"
        onEscapeKeyDown={(event) => event.preventDefault()}
        onInteractOutside={(event) => event.preventDefault()}
      >
        <div>
          <p className="text-xs font-medium tracking-wide text-text-secondary uppercase">
            Run task
          </p>
          <DialogTitle className="mt-1">{props.taskTitle}</DialogTitle>
          <p className="mt-2 text-sm leading-6 text-text-secondary">
            Add optional context for the task generated by this template run.
          </p>
        </div>

        <label className="mt-4 grid gap-1 text-sm text-text-secondary">
          Run context
          <Textarea
            className="min-h-32 resize-y"
            placeholder="Anything the specialist should know for this specific run..."
            value={contextText}
            onChange={(event) => setContextText(event.target.value)}
          />
        </label>

        <div className="mt-4 grid gap-2 text-sm text-text-secondary">
          <label
            className={buttonVariants({ variant: "secondary", className: "w-fit cursor-pointer" })}
          >
            Add attachments
            <input
              accept=".txt,.md,.csv,.json,.pdf,.png,.jpg,.jpeg,.webp,.gif"
              className="sr-only"
              multiple
              onChange={(event) => void handleUpload(event)}
              type="file"
            />
          </label>
          {attachments.length > 0 ? (
            <ul className="grid gap-2">
              {attachments.map((attachment) => (
                <li
                  className="rounded-lg border border-border bg-surface p-2 text-xs text-text-secondary"
                  key={`${attachment.filename}:${String(attachment.sizeBytes)}`}
                >
                  {attachment.filename} · {formatBytes(attachment.sizeBytes ?? 0)}
                </li>
              ))}
            </ul>
          ) : null}
        </div>

        <div className="mt-5 flex flex-wrap justify-end gap-2">
          <Button variant="secondary" disabled={props.busy} onClick={props.onCancel} type="button">
            Cancel
          </Button>
          <Button
            data-testid="task-run-context-submit"
            disabled={props.busy}
            onClick={handleRun}
            type="button"
          >
            Run task
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function readFileAsDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result === "string") {
        resolve(reader.result);
        return;
      }

      reject(new Error("Failed to read attachment."));
    };
    reader.onerror = () => reject(reader.error ?? new Error("Failed to read attachment."));
    reader.readAsDataURL(file);
  });
}

function formatBytes(value: number): string {
  if (value < 1024) return `${String(value)} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
  return `${(value / 1024 / 1024).toFixed(1)} MB`;
}
