export const SPECIALIST_ICON_OPTIONS = [
  { label: "Bot", value: "icon:bot" },
  { label: "Sparkles", value: "icon:sparkles" },
  { label: "Brain", value: "icon:brain" },
  { label: "Code", value: "icon:code2" },
  { label: "Terminal", value: "icon:terminal" },
  { label: "Search", value: "icon:search" },
  { label: "Rocket", value: "icon:rocket" },
  { label: "Wrench", value: "icon:wrench" },
  { label: "Shield", value: "icon:shield" },
  { label: "Lightbulb", value: "icon:lightbulb" },
  { label: "Microscope", value: "icon:microscope" },
  { label: "Briefcase", value: "icon:briefcase" },
  { label: "Folder", value: "icon:folderkanban" },
  { label: "Files", value: "icon:filetext" },
  { label: "Globe", value: "icon:globe" },
  { label: "Bug", value: "icon:bug" },
  { label: "Flask", value: "icon:flaskconical" },
  { label: "Message", value: "icon:messagesquare" },
  { label: "Support", value: "icon:headphones" },
  { label: "Builder", value: "icon:hammer" },
  { label: "Image", value: "icon:image" },
  { label: "Helper", value: "icon:userround" },
  { label: "Math", value: "icon:calculator" },
] as const;

export const SPECIALIST_EMOJI_OPTIONS = [
  "🤖",
  "🧠",
  "✨",
  "🛠️",
  "🚀",
  "🧪",
  "🔎",
  "🧾",
  "📁",
  "💡",
  "🧑‍💻",
  "📝",
  "📣",
  "🎯",
  "🧭",
  "🛡️",
  "🌐",
  "📊",
  "🎨",
] as const;
