export const queryKeys = {
  documentTree: ["document-tree"] as const,
  documentContent: (path: string) => ["document-content", path] as const,
  engineStatus: ["engine-status"] as const,
  systemVersion: ["system-version"] as const,
  systemUpdatePreferences: ["system-update-preferences"] as const,
  taskArtifactSharingPreferences: ["task-artifact-sharing-preferences"] as const,
  providers: ["providers"] as const,
  mcpServers: ["mcp-servers"] as const,
  secrets: ["secrets"] as const,
  apiTokens: ["api-tokens"] as const,
  specialists: ["specialists"] as const,
  specialistCatalog: ["specialist-catalog"] as const,
  specialistBySlug: (slug: string) => ["specialist", slug] as const,
  specialistCustomTools: (specialistId: string) =>
    ["specialist-custom-tools", specialistId] as const,
  customTools: ["custom-tools"] as const,
  workspaceSkills: ["workspace-skills"] as const,
  conversationSnapshot: (agentId: string) => ["conversation-snapshot", agentId] as const,
  conversation: (agentId: string, conversationId: string) =>
    ["conversation", agentId, conversationId] as const,
  conversations: (agentId: string) => ["conversations", agentId] as const,
  conversationMedia: (conversationId: string) => ["conversation-media", conversationId] as const,
  conversationSystemPrompts: (conversationId: string) =>
    ["conversation-system-prompts", conversationId] as const,
  activities: ["activities"] as const,
  activitiesResolved: ["activities", "resolved"] as const,
  systemPrompts: ["system-prompts"] as const,
  systemPrompt: (id: string) => ["system-prompt", id] as const,
  tasks: (query?: Record<string, unknown>) => ["tasks", query ?? {}] as const,
  taskArchive: ["task-archive"] as const,
  taskTemplates: ["task-templates"] as const,
  taskTemplate: (templateId: string) => ["task-template", templateId] as const,
  taskTemplateTasks: (templateId: string) => ["task-template-tasks", templateId] as const,
  task: (taskId: string) => ["task", taskId] as const,
  taskFeedback: (taskId: string) => ["task-feedback", taskId] as const,
  taskSubtasks: (taskId: string) => ["task-subtasks", taskId] as const,
  taskSubtaskProgress: (taskIds: string[]) => ["task-subtask-progress", taskIds] as const,
  taskRuns: (taskId: string) => ["task-runs", taskId] as const,
  taskRun: (taskId: string, runId: string) => ["task-run", taskId, runId] as const,
  taskRunFollowups: (taskId: string, runId: string) =>
    ["task-run-followups", taskId, runId] as const,
  conversationArtifacts: (conversationId: string) =>
    ["conversation-artifacts", conversationId] as const,
  taskRunSession: (taskId: string, runId: string) => ["task-run-session", taskId, runId] as const,
  activeTaskRuns: ["active-task-runs"] as const,
  taskSchedulerState: ["task-scheduler-state"] as const,
};
